steps:
  # ステップ1: サービス存在チェック
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== サービス存在チェック ==="
        
        # Cloud Runサービスとして存在するかチェック
        if gcloud run services describe hello-world --region=${_REGION} 2>/dev/null; then
          _SERVICE_STATUS="existing"
          
          echo "現在の設定:"
          gcloud run services describe hello-world --region=${_REGION} \
            --format="table(status.url,status.ingress,spec.template.spec.containers[0].resources.limits.memory)"
        else
          echo "📝 既存サービスが見つかりません"
          _SERVICE_STATUS="not existing"
        fi
        
        echo "サービス状態: ${_SERVICE_STATUS}"
        
        echo ""
        echo "=== 設定値 ==="
        echo "リージョン: ${_REGION}"
        echo "メモリ: ${_MEMORY}"
        echo "タイムアウト: ${_TIMEOUT}"
        echo "最大インスタンス: ${_MAX_INSTANCES}"
        echo "環境: ${_ENVIRONMENT}"
    id: 'check-service'

  # ステップ2: 新規サービス作成/ 既存サービス更新
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |        
        if [ "${_SERVICE_STATUS}" = "existing" ]; then
          echo "=== 既存サービスの更新 ==="
          
          gcloud run services update hello-world \
            --region=${_REGION} \
            --no-allow-unauthenticated \
            --ingress=all \
            --memory=${_MEMORY} \
            --timeout=${_TIMEOUT} \
            --max-instances=${_MAX_INSTANCES} \
            --min-instances=${_MIN_INSTANCES} \
            --set-env-vars=ENVIRONMENT=${_ENVIRONMENT},ACCESS_TYPE=authenticated \
            --verbosity=info
          
          echo "✅ 既存サービス更新完了"
        else
          gcloud functions deploy hello-world \
            --gen2 \
            --runtime=python311 \
            --region=${_REGION} \
            --source=./cloud_run_functions \
            --entry-point=hello_world \
            --trigger-http \
            --no-allow-unauthenticated \
            --ingress-settings=all \
            --memory=${_MEMORY} \
            --timeout=${_TIMEOUT} \
            --max-instances=${_MAX_INSTANCES} \
            --min-instances=${_MIN_INSTANCES} \
            --set-env-vars=ENVIRONMENT=${_ENVIRONMENT},ACCESS_TYPE=authenticated \
            --verbosity=info
          
          echo "✅ 新規関数作成完了"
        fi
    id: 'create-or-update-service'
    waitFor: ['check-service']

substitutions:
  _REGION: 'asia-northeast1'
  _MEMORY: '256Mi'
  _TIMEOUT: '60s'
  _MAX_INSTANCES: '5'
  _MIN_INSTANCES: '0'
  _ENVIRONMENT: 'development'
  _SERVICE_STATUS: ''

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'